[package]
name = "rust_can_firewall"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_can_firewall"
crate-type = ["cdylib"]

[dependencies]
# Κλειδώνουμε την έκδοση για να μην έχουμε εκπλήξεις
pyo3 = { version = "0.21.0", features = ["extension-module"] }